# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_user_pb2 as agent__user__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentUserServiceStub(object):
    """供 private_chef_server 调用：仅携带用户 ID，agent 返回确认消息。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingUser = channel.unary_unary(
                '/privatechef.agent.AgentUserService/PingUser',
                request_serializer=agent__user__pb2.PingUserRequest.SerializeToString,
                response_deserializer=agent__user__pb2.PingUserResponse.FromString,
                _registered_method=True)


class AgentUserServiceServicer(object):
    """供 private_chef_server 调用：仅携带用户 ID，agent 返回确认消息。
    """

    def PingUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentUserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingUser': grpc.unary_unary_rpc_method_handler(
                    servicer.PingUser,
                    request_deserializer=agent__user__pb2.PingUserRequest.FromString,
                    response_serializer=agent__user__pb2.PingUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privatechef.agent.AgentUserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('privatechef.agent.AgentUserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentUserService(object):
    """供 private_chef_server 调用：仅携带用户 ID，agent 返回确认消息。
    """

    @staticmethod
    def PingUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privatechef.agent.AgentUserService/PingUser',
            agent__user__pb2.PingUserRequest.SerializeToString,
            agent__user__pb2.PingUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
