# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61gent_user.proto\x12\x11privatechef.agent\"\"\n\x0fPingUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"#\n\x10PingUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2g\n\x10\x41gentUserService\x12S\n\x08PingUser\x12\".privatechef.agent.PingUserRequest\x1a#.privatechef.agent.PingUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGUSERREQUEST']._serialized_start=39
  _globals['_PINGUSERREQUEST']._serialized_end=73
  _globals['_PINGUSERRESPONSE']._serialized_start=75
  _globals['_PINGUSERRESPONSE']._serialized_end=110
  _globals['_AGENTUSERSERVICE']._serialized_start=112
  _globals['_AGENTUSERSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
